# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[ruby]
disabled = true

[nix_shell]
disabled = true

[python]
disabled = true

[buf]
disabled = true

[nodejs]
format = '[($version )]($style)'

[golang]
format = '[($version )]($style)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ''
truncation_length = 25

[git_metrics]
disabled = false 
